---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Read data {#Read Data}
## Load packages

```{r}

source("./00_dependencies.R")

```


## Load data

```{r}

####-----  List samples
samples <- str_replace(str_sort(list.files("../data/counts_mx"), numeric = TRUE),
                       "_filtered_feature_bc_matrix",
                       "")

cat("Samples: \n", samples)


####----- Create a named vector with paths to samples
samples.dirs <- sapply(samples, function(i) {
  d10x <- file.path('../data/counts_mx',
                    paste0(i, '_filtered_feature_bc_matrix'))
  d10x
})

cat("Sample directories: \n", samples.dirs)


####----- Read count matrices
gex_data <- Read10X(data.dir = samples.dirs,
                    unique.features = TRUE,
                    strip.suffix = TRUE)
str(gex_data)

####----- Create seurat object
gex <- CreateSeuratObject(gex_data, 
                          project = "pSS",
                          min.cells = 0,
                          min.features = 0,
                          names.field = 1)

counts <- as.data.frame(table(gex@meta.data$orig.ident))
colnames(counts) <- c("sample", "cells")
write.csv(counts, "../results/cellcounts_GEX1_RAW.txt")


####-----  rm tmp objects
rm(samples, samples.dirs, gex_data)

####-----  change orig.ident for P007 and P008; libraries were generated and sequenced twice
gex@meta.data$orig.ident <- gsub("P007[ab]", "P007", gex@meta.data$orig.ident)
gex@meta.data$orig.ident <- gsub("P008[ab]", "P008", gex@meta.data$orig.ident)

```


## add pheno info

```{r}

pheno <- read.table("../suppl/pheno/pSS_pheno_210623.csv", sep = ";", header = TRUE)
colnames(pheno)[c(1, 3)] <- c("Sample_id", "orig.ident")
pheno$orig.ident <- gsub("P007[ab]", "P007", pheno$orig.ident)
pheno$orig.ident <- gsub("P008[ab]", "P008", pheno$orig.ident)
pheno <- unique(pheno[, c(1, 3, 5, 7:8, 11:12)])
head(pheno); dim(pheno)

meta.data.tmp <- gex@meta.data
meta.data.tmp$cell <- row.names(meta.data.tmp)
meta.data.tmp <- merge(meta.data.tmp, pheno, by = "orig.ident", all.x = TRUE)
row.names(meta.data.tmp) <- meta.data.tmp$cell
meta.data.tmp$cell <- NULL

gex <- AddMetaData(gex, meta.data.tmp); head(gex@meta.data); table(gex@meta.data$orig.ident)

Idents(object = gex) <- "orig.ident"


```


## Add patient group

```{r}

gex$patient_group <- paste0(ifelse(gex$SSA == "YES", "SSA", ""), 
                            "_", 
                            ifelse(gex$SSB == "YES", "SSB", ""))

pat_annot <- c(SSAB = "SSA_SSB", SSA = "SSA_", DNEG="NA_NA", DNEG="_")
gex$patient_group <- names(pat_annot)[match(gex$patient_group, pat_annot)]
gex$patient_group[grep("^C00", gex$orig.ident) ] <- "CTRL"
gex$patient_group <- factor(gex$patient_group, levels = c("CTRL", "DNEG", "SSA", "SSAB"))

```


## save rds GEX1_RAW.rds

```{r include = FALSE}

saveRDS(gex, file = "../results/GEX1_RAW.rds")
#gex <- readRDS("../results/GEX1_RAW.rds")

cat("GEX_RAW size: \n")
print(object.size(gex), units = "GB")

gex

```


## Print sessionInfo()

```{r}

sessionInfo()

```

