# VDJ analysis pt1 {#VDJ1}

## Load packages

```{r}
source("./00_dependencies.R")

library(alakazam)
library(shazam)
library(dplyr)
library(ggplot2)


```


## Load Seurat object

```{r}

gex <- readRDS("../results/GEX_DIMRED2.rds"); gex

```


## Load output from Immcantation and perform mutation analysis

```{r}

library(airr)
files_B <- list.files(../data/clono_B_VDJ/*/immcantation_out/*germ-pass.tsv, full.names = TRUE)
outfile <- NULL
for (i in files_B) {
  
  tmp <- read_rearrangement(i)
  
  
  
  if (is.null(outfile)) {
    outfile <- db
  } else {
    outfile <- rbind(outfile, db)
  }
  
}

#dbfiles <- dir(opt$genotyped_path, 'germ-pass[.]tab', full.names=T)
airr_rearrangement <- read_rearrangement(example_data)
db <- readChangeoDb(g_file)
  
# calculate mutation counts and frequencies
# mutaion counts per individual regions
db <- observedMutations(db, sequenceColumn="SEQUENCE_IMGT", germlineColumn="GERMLINE_IMGT_D_MASK",
                          frequency=F, regionDefinition=IMGT_V_BY_REGIONS, combine=F)


list.files()

df <- 


```


## Subset and reformat immcantation DF and integrate with Seurat object

```{r}



```


## Save rds GEX_BCELLS

```{r}

saveRDS(gex, file = "../results/GEX_BVDJ.rds")


```


## Print sessionInfo()

```{r}

sessionInfo()


```



