---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Visualization {#Viz}

## Load packages

```{r}

source("./00_dependencies.R")

```


## Load Seurat object

```{r}

gex <- readRDS("../results/GEX_BVDJ.rds"); gex

```


# patients per cluster

```{r}

table(gex$orig.ident, gex$seurat_clusters)
table(gex$patient_group, gex$seurat_clusters)


mypal <- RColorBrewer::brewer.pal(4,"Set3")

res <- table(list(gex$seurat_clusters, gex$patient_group))
res <- t(res)
res <- res[,order(colSums(res),decreasing = T)]
res2 <- t( t(res) / colSums(res) )
res3 <- res / rowSums(res)
res4 <- t( t(res3) / colSums(res3) )

pdf(file = paste0("../results/cluster_patient_abundance.pdf"),
    width = 8,height = 5,useDingbats = F)

mypar(4,1,mar=c(2,4,0,1))

barplot(res,las=1,ylim=c(0,max(colSums(res))*1.3),col = mypal,ylab = "total cell numbers\n",xaxs="i",yaxs="i",space = 0)

barplot(res3,las=1,ylim=c(0,max(colSums(res3))*1.3),col = mypal,ylab = "percentage\n",xaxs="i",yaxs="i",space = 0)

barplot(res2*100,las=1,col=mypal,ylab="percentage\n",xaxs="i",yaxs="i",space = 0)

barplot(res4*100,las=1,col=mypal,ylab="percentage\n",xaxs="i",yaxs="i",space = 0)

legend("topright",legend = rownames(res), bty = "n",fill = mypal)

dev.off()


DimPlot(gex, split.by = "patient_group", reduction = "umap_2", ncol = 2)


#Four non-overlapping groups
#1. SSA+/SSB+
#2. SSA+/SSB-
#3. SSA-/SSB-
#4. CTRL


```


## 

```{r}



```


## 

```{r}



```




## Save rds GEX_xxx

```{r}

saveRDS(gex, file = "../results/GEX_xxx.rds")

```


## Print sessionInfo()

```{r}

sessionInfo()

```



