---
output: html_document
editor_options: 
  chunk_output_type: console
---
# PCA per sample variables {#PCA}

## Load packages

```{r}

source("./00_dependencies.R")

```


## Load Seurat object

```{r}

gex <- readRDS("../results/GEX7_BVDJ.rds")

```


## reduce gex size

```{r}
# gex.meta <- gex@meta.data[(gex$cluster_cellType_manual_fine == "DN1_ID3" |
#                           gex$cluster_cellType_manual_fine == "DN2" |
#                           gex$cluster_cellType_manual_fine == "DN2_CXCR3" |
#                           gex$cluster_cellType_manual_fine == "DN2_ITGAX" |
#                           gex$cluster_cellType_manual_fine == "DN4" |
#                           gex$cluster_cellType_manual_fine == "Memory_Cl" |
#                           gex$cluster_cellType_manual_fine == "Memory_IgM" |
#                           gex$cluster_cellType_manual_fine == "Memory_IgM_ALOX5" |
#                           gex$cluster_cellType_manual_fine == "Memory_IgM_CD1C" |
#                           gex$cluster_cellType_manual_fine == "Naive" |
#                           gex$cluster_cellType_manual_fine == "Naive_IFN" |
#                           gex$cluster_cellType_manual_fine == "Naive_Transitional"), ]

gex.slim <- gex; rm(gex)
gex.slim@assays$RNA@scale.data <- matrix()
to_remove <- c("pca_1", "pca_2", "scpred", "scpred_projection", 
               "harmony_1", "harmony_2", "umap_1", "umap_2_3d")
gex.slim@reductions <- gex.slim@reductions[!(names(gex.slim@reductions) %in% to_remove)]

gex.slim <- gex.slim[, (gex.slim$cluster_cellType_manual_fine == "DN1_ID3" |
                        gex.slim$cluster_cellType_manual_fine == "DN2" |
                        gex.slim$cluster_cellType_manual_fine == "DN2_CXCR3" |
                        gex.slim$cluster_cellType_manual_fine == "DN2_ITGAX" |
                        gex.slim$cluster_cellType_manual_fine == "DN4" |
                        gex.slim$cluster_cellType_manual_fine == "Memory_Cl" |
                        gex.slim$cluster_cellType_manual_fine == "Memory_IgM" |
                        gex.slim$cluster_cellType_manual_fine == "Memory_IgM_ALOX5" |
                        gex.slim$cluster_cellType_manual_fine == "Memory_IgM_CD1C" |
                        gex.slim$cluster_cellType_manual_fine == "Naive" |
                        gex.slim$cluster_cellType_manual_fine == "Naive_IFN" |
                        gex.slim$cluster_cellType_manual_fine == "Naive_Transitional")]


```


## Patient Meta Data

```{r}

pheno <- read_excel("/Users/gusarv/Documents/projekt/SjS/Info/pheno/24_clin_data_all_220411GN_forR.xlsx")
colnames(pheno)

pheno <- pheno[, c("Single cell_Sample_id_publ", 
                   "Age symptom onset",
                   "Age diagnosis",
                   "First symptoms",
                   "ANA",
                   "SSA Ro52",
                   "SSA Ro60",
                   "SSA",
                   "SSB",
                   "SSA and SSB",
                   "RNP",
                   "Sm",
                   "RF",
                   "Focus score Greenspan",
                   "Anemia Hb<120g/L",
                   "Leucopenia <4.0x109/L",
                   "Lymphopenia <1.0x109/L",
                   "P-IgG >15g/L",
                   "Raynaud",
                   "Arthritis",
                   "Purpura",
                   "Major salivary gland swelling",
                   "Hypothyreoidism",
                   "Treatment at B cell sampling, HCQ",
                   "Prednisolone")]

colnames(pheno)[1] <- "orig.ident"

pheno <- pheno %>% add_row(orig.ident = c("C001", "C002", "C003", "C004")) %>% arrange(orig.ident)
colnames(pheno) <- gsub(" ", "_", colnames(pheno))


## cleanup pheno data
pheno <- pheno[, c(-2,-3,-14)]

pheno$arthralgia <- ifelse(grepl("arthralgia", pheno$First_symptoms), "YES", "NO")
pheno$arthritis <- ifelse(grepl("arthritis", pheno$First_symptoms), "YES", "NO")
pheno$hemiparesis <- ifelse(grepl("hemiparesis", pheno$First_symptoms), "YES", "NO")
pheno$myalgia <- ifelse(grepl("myalgia", pheno$First_symptoms), "YES", "NO")
pheno$sicca <- ifelse(grepl("sicc", pheno$First_symptoms), "YES", "NO")
pheno$erythema_nodosum <- ifelse(grepl("erythema", pheno$First_symptoms), "YES", "NO")
pheno$major_salivary_gland_swelling <- ifelse(grepl("salivary", pheno$First_symptoms), "YES", "NO")
pheno$Raynaud <- ifelse(grepl("Raynaud", pheno$First_symptoms), "YES", "NO")
pheno$pleuritis_entesitis_tendinitis <- ifelse(grepl("pleuritis", pheno$First_symptoms), "YES", "NO")

pheno <- pheno[, c(-2)]
pheno[is.na(pheno)] <- "NO"

pheno2 <- read.table("../suppl/pheno/pSS_pheno_211208.csv", sep = ",", header = TRUE)
colnames(pheno2)[c(1, 3)] <- c("Sample_id", "orig.ident")
pheno2$orig.ident <- gsub("P007[ab]", "P007", pheno2$orig.ident)
pheno2$orig.ident <- gsub("P008[ab]", "P008", pheno2$orig.ident)
pheno2 <- unique(pheno2[, c(1, 3, 5, 7:8, 11:12)])
head(pheno2); dim(pheno2)

pheno2$patient_group <- paste0(ifelse(pheno2$SSA == "YES", "SSA", ""),
                            "_",
                            ifelse(pheno2$SSB == "YES", "SSB", ""))
pat_annot <- c(SSAB = "SSA_SSB", SSA = "SSA_", DNEG="NA_NA", DNEG="_")
pheno2$patient_group <- names(pat_annot)[match(pheno2$patient_group, pat_annot)]
pheno2$patient_group[grep("^C00", pheno2$orig.ident) ] <- "CTRL"
pheno2$patient_group <- factor(pheno2$patient_group, levels = c("CTRL", "DNEG", "SSA", "SSAB"))

pheno2 <- pheno2[order(pheno2$orig.ident),]


pheno <- cbind(pheno, pheno2$patient_group)
colnames(pheno)[30] <- "patient_group"

pheno <- pheno[-28,] # remove P024


#pheno_tmp <- pheno
#pheno <- pheno_tmp

pheno[pheno == "NO"] <- 0
pheno[pheno == "YES"] <- 1
pheno[pheno == "MD"] <- NA

rownames(pheno) <- pheno$orig.ident
pheno[, 2:29] <- sapply(pheno[, 2:29], as.numeric)
#colnames(pheno); colSums(pheno[, 2:29], na.rm = T)
head(pheno)

#remove variables only present in one sample
pheno <- pheno[, c(1, (1 + which(colSums(pheno[,2:29], na.rm = TRUE) > 2, )), 30)]

str(pheno)
```


## celltype frequencies per patient

```{r}

#cellType_manual_fine
cells_fine <- dplyr::select(gex.slim@meta.data,
                   orig.ident,
                   cluster_cellType_manual_fine) %>%
  add_count(orig.ident, 
            cluster_cellType_manual_fine, 
            .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, 
                cluster_cellType_manual_fine, 
                per) %>%
  pivot_wider(names_from = cluster_cellType_manual_fine, 
              values_from = per)

colnames(cells_fine)[2:ncol(cells_fine)] <- paste0(colnames(cells_fine)[2:ncol(cells_fine)], "_fine_perc")

#cellType_manual_main
cells_main <- dplyr::select(gex.slim@meta.data, 
                       orig.ident, 
                       cluster_cellType_manual_main) %>% 
  add_count(orig.ident, 
            cluster_cellType_manual_main, 
            .drop = FALSE) %>%
  distinct() %>% 
  group_by(orig.ident) %>% 
  mutate(per =  prop.table(n)) %>%
  drop_na() %>% 
  dplyr::select(orig.ident, 
                cluster_cellType_manual_main, 
                per) %>% 
  pivot_wider(names_from = cluster_cellType_manual_main, 
              values_from = per) 

colnames(cells_main)[2:ncol(cells_main)] <- paste0(colnames(cells_main)[2:ncol(cells_main)], "_main_perc")

celltypes <- inner_join(cells_main, cells_fine) 


```


## VDJ percentages per celltype

```{r}

# IGHV
IGHV <- dplyr::select(gex.slim@meta.data,
                           orig.ident,
                           IGHV) %>%
  add_count(orig.ident,
            IGHV,
            .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, IGHV, per) %>%
  pivot_wider(
    names_from = c(IGHV),
    values_from = per,
    values_fill = 0
  )

# IGHV gene per celltypeFine
IGHV_fine <- dplyr::select(gex.slim@meta.data,
                           orig.ident,
                           cluster_cellType_manual_fine,
                           IGHV) %>%
  add_count(orig.ident,
            cluster_cellType_manual_fine,
            IGHV,
            .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident,
           cluster_cellType_manual_fine) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, cluster_cellType_manual_fine, IGHV, per) %>%
  pivot_wider(
    names_from = c(IGHV, cluster_cellType_manual_fine),
    values_from = per,
    values_fill = 0
  )

colnames(IGHV_fine)[2:ncol(IGHV_fine)] <-
  paste0(colnames(IGHV_fine)[2:ncol(IGHV_fine)], "_fine")

# IGHV gene per celltypeMine
IGHV_main <- dplyr::select(gex.slim@meta.data,
                           orig.ident,
                           cluster_cellType_manual_main,
                           IGHV) %>%
  add_count(orig.ident, cluster_cellType_manual_main, IGHV, .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident, cluster_cellType_manual_main) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident,
                cluster_cellType_manual_main,
                IGHV,
                per) %>%
  pivot_wider(
    names_from = c(IGHV, cluster_cellType_manual_main),
    values_from = per,
    values_fill = 0
  )

colnames(IGHV_main)[2:ncol(IGHV_main)] <-
  paste0(colnames(IGHV_main)[2:ncol(IGHV_main)], "_main")
 

# IGHD
IGHD <- dplyr::select(gex.slim@meta.data,
                           orig.ident,
                           IGHD) %>%
  add_count(orig.ident,
            IGHD,
            .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, IGHD, per) %>%
  pivot_wider(
    names_from = c(IGHD),
    values_from = per,
    values_fill = 0
  )

# IGHD gene per celltypeFine
IGHD_fine <- dplyr::select(gex.slim@meta.data,
                           orig.ident,
                           cluster_cellType_manual_fine,
                           IGHD) %>%
  add_count(orig.ident, cluster_cellType_manual_fine, IGHD, .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident, cluster_cellType_manual_fine) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, cluster_cellType_manual_fine, IGHD, per) %>%
  pivot_wider(
    names_from = c(IGHD, cluster_cellType_manual_fine),
    values_from = per,
    values_fill = 0
  )

colnames(IGHD_fine)[2:ncol(IGHD_fine)] <-
  paste0(colnames(IGHD_fine)[2:ncol(IGHD_fine)], "_fine")

# IGHD gene per celltypeMine
IGHD_main <- dplyr::select(gex.slim@meta.data,
                           orig.ident,
                           cluster_cellType_manual_main,
                           IGHD) %>%
  add_count(orig.ident, cluster_cellType_manual_main, IGHD, .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident, cluster_cellType_manual_main) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, cluster_cellType_manual_main, IGHD, per) %>%
  pivot_wider(
    names_from = c(IGHD, cluster_cellType_manual_main),
    values_from = per,
    values_fill = 0
  )

colnames(IGHD_main)[2:ncol(IGHD_main)] <-
  paste0(colnames(IGHD_main)[2:ncol(IGHD_main)], "_main")

# IGHJ
IGHJ <- dplyr::select(gex.slim@meta.data,
                           orig.ident,
                           IGHJ) %>%
  add_count(orig.ident,
            IGHJ,
            .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, IGHJ, per) %>%
  pivot_wider(
    names_from = c(IGHJ),
    values_from = per,
    values_fill = 0
  )


# IGHJ gene per celltypeFine
IGHJ_fine <- dplyr::select(gex.slim@meta.data,
                           orig.ident,
                           cluster_cellType_manual_fine,
                           IGHJ) %>%
  add_count(orig.ident, cluster_cellType_manual_fine, IGHJ, .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident, cluster_cellType_manual_fine) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, cluster_cellType_manual_fine, IGHJ, per) %>%
  pivot_wider(
    names_from = c(IGHJ, cluster_cellType_manual_fine),
    values_from = per,
    values_fill = 0
  )

colnames(IGHJ_fine)[2:ncol(IGHJ_fine)] <-
  paste0(colnames(IGHJ_fine)[2:ncol(IGHJ_fine)], "_fine")


# IGHJ gene per celltypeMain
IGHJ_main <- dplyr::select(gex.slim@meta.data,
                           orig.ident,
                           cluster_cellType_manual_main,
                           IGHJ) %>%
  add_count(orig.ident, cluster_cellType_manual_main, IGHJ, .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident, cluster_cellType_manual_main) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, cluster_cellType_manual_main, IGHJ, per) %>%
  pivot_wider(
    names_from = c(IGHJ, cluster_cellType_manual_main),
    values_from = per,
    values_fill = 0
  )

colnames(IGHJ_main)[2:ncol(IGHJ_main)] <-
  paste0(colnames(IGHJ_main)[2:ncol(IGHJ_main)], "_main")

# IGHC
c_gene_10x <- dplyr::select(gex.slim@meta.data,
                           orig.ident,
                           c_gene_10x) %>%
  add_count(orig.ident,
            c_gene_10x,
            .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, c_gene_10x, per) %>%
  pivot_wider(
    names_from = c(c_gene_10x),
    values_from = per,
    values_fill = 0
  )


# IGHC gene per celltypeFine
c_gene_10x_fine <- dplyr::select(gex.slim@meta.data,
                                 orig.ident,
                                 cluster_cellType_manual_fine,
                                 c_gene_10x) %>%
  add_count(orig.ident,
            cluster_cellType_manual_fine,
            c_gene_10x, .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident, cluster_cellType_manual_fine) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, cluster_cellType_manual_fine, c_gene_10x, per) %>%
  pivot_wider(
    names_from = c(c_gene_10x, cluster_cellType_manual_fine),
    values_from = per,
    values_fill = 0
  )

colnames(c_gene_10x_fine)[2:ncol(c_gene_10x_fine)] <-
  paste0(colnames(c_gene_10x_fine)[2:ncol(c_gene_10x_fine)], "_fine")

# IGHC gene per celltypeMine
c_gene_10x_main <- dplyr::select(gex.slim@meta.data,
                                 orig.ident,
                                 cluster_cellType_manual_main,
                                 c_gene_10x) %>%
  add_count(orig.ident,
            cluster_cellType_manual_main,
            c_gene_10x, .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident, cluster_cellType_manual_main) %>%
  mutate(per =  prop.table(n)) %>%
  drop_na() %>%
  dplyr::select(orig.ident, cluster_cellType_manual_main, c_gene_10x, per) %>%
  pivot_wider(
    names_from = c(c_gene_10x, cluster_cellType_manual_main),
    values_from = per,
    values_fill = 0
  )

colnames(c_gene_10x_main)[2:ncol(c_gene_10x_main)] <-
  paste0(colnames(c_gene_10x_main)[2:ncol(c_gene_10x_main)], "_main")

IGHVDJ_cell <-
  inner_join(IGHV_fine, IGHV_main, by = "orig.ident") %>%
  inner_join(IGHD_fine, by = "orig.ident") %>%
  inner_join(IGHD_main, by = "orig.ident") %>%
  inner_join(IGHJ_fine, by = "orig.ident") %>%
  inner_join(IGHJ_main, by = "orig.ident") %>%
  inner_join(c_gene_10x_fine, by = "orig.ident") %>%
  inner_join(c_gene_10x_main, by = "orig.ident")


```


## IFN score

```{r}

# get hallmark gene sets
HM <- getGenesets("/Users/gusarv/Downloads/MSigDB_Hallmark_2020.txt")

IFN <- unique(c(HM$`Interferon Alpha Response`, 
                HM$`Interferon Gamma Response`))
#IFNA <- HM$`Interferon Alpha Response`
#IFNG <- HM$`Interferon Gamma Response`

#gex.slim[rownames(gex.slim) %in% IFN, ]
#gex.slim@assays$RNA@data[rownames(gex.slim) %in% IFN, ]

#cluster_cellType_manual_fine
ALL_expr <- AggregateExpression(gex.slim, 
                                slot = "counts",
                                group.by = c("cluster_cellType_manual_fine", "orig.ident"))

ALL_expr <- as.data.frame(ALL_expr$RNA)
IFN_expr <- ALL_expr[IFN, ]
ALL_expr <- ALL_expr[!(rownames(ALL_expr) %in% IFN), ]

IFN_fine <- as.data.frame(colSums(IFN_expr, na.rm = TRUE) / colSums(ALL_expr, na.rm = TRUE))
colnames(IFN_fine)[1] <- "IFN_score"
IFN_fine$cluster_cellType_manual_fine <- substr(rownames(IFN_fine), 1, nchar(rownames(IFN_fine)) - 5)
IFN_fine$orig.ident <- substr(rownames(IFN_fine), nchar(rownames(IFN_fine)) - 3, nchar(rownames(IFN_fine)))

IFN_fine <- pivot_wider(IFN_fine, 
                        names_from = cluster_cellType_manual_fine, 
                        values_from = IFN_score) 

colnames(IFN_fine)[2:ncol(IFN_fine)] <- paste0(colnames(IFN_fine)[2:ncol(IFN_fine)], "_fine_IFNscore")


#cluster_cellType_manual_main
ALL_expr <- AggregateExpression(gex.slim, 
                                slot = "counts",
                                group.by = c("cluster_cellType_manual_main", "orig.ident"))

ALL_expr <- as.data.frame(ALL_expr$RNA)
IFN_expr <- ALL_expr[IFN, ]
ALL_expr <- ALL_expr[!(rownames(ALL_expr) %in% IFN), ]

IFN_main <- as.data.frame(colSums(IFN_expr, na.rm = TRUE) / colSums(ALL_expr, na.rm = TRUE))
colnames(IFN_main)[1] <- "IFN_score"
IFN_main$cluster_cellType_manual_main <- substr(rownames(IFN_main), 1, nchar(rownames(IFN_main)) - 5)
IFN_main$orig.ident <- substr(rownames(IFN_main), nchar(rownames(IFN_main)) - 3, nchar(rownames(IFN_main)))

IFN_main <- pivot_wider(IFN_main, 
                        names_from = cluster_cellType_manual_main, 
                        values_from = IFN_score) 

colnames(IFN_main)[2:ncol(IFN_main)] <- paste0(colnames(IFN_main)[2:ncol(IFN_main)], "_main_IFNscore")

IFN_score <- inner_join(IFN_main, IFN_fine)


```


## mutated VDJ bp per celltype 

```{r}

mu_fine <- gex.slim@meta.data %>% 
  select(orig.ident, cluster_cellType_manual_fine, mu_freq_total, c_gene_10x) %>%
  drop_na() %>%
  group_by(orig.ident, cluster_cellType_manual_fine) %>% 
  summarise(mu_mean_fine = mean(mu_freq_total, )) %>% 
  pivot_wider(names_from = cluster_cellType_manual_fine, 
              values_from = mu_mean_fine,
              values_fill = 0)

colnames(mu_fine)[2:ncol(mu_fine)] <- paste0(colnames(mu_fine)[2:ncol(mu_fine)], "_fine_mu")


mu_main <- gex.slim@meta.data %>% 
  select(orig.ident, cluster_cellType_manual_main, mu_freq_total, c_gene_10x) %>%
  drop_na() %>%
  group_by(orig.ident, cluster_cellType_manual_main) %>% 
  summarise(mu_mean_main = mean(mu_freq_total, )) %>% 
  pivot_wider(names_from = cluster_cellType_manual_main, 
              values_from = mu_mean_main,
              values_fill = 0)

colnames(mu_main)[2:ncol(mu_main)] <- paste0(colnames(mu_main)[2:ncol(mu_main)], "_main_mu")

mu_freq <- inner_join(mu_main, mu_fine)


```


## clonotypes % 

```{r}

gex.slim@meta.data$cloneType_airr_short <- gex.slim@meta.data$cloneType_airr
gex.slim@meta.data$cloneType_airr_short <- gsub(" \\((.*)\\).*", "", gex.slim@meta.data$cloneType_airr_short)
  

# clonotypes for all cells per patients 
ctype_all <- gex.slim@meta.data %>% 
  select(orig.ident, cloneType_airr_short, c_gene_10x) %>%
  drop_na() %>%
  select(orig.ident, cloneType_airr_short)  %>%
  add_count(orig.ident, 
            cloneType_airr_short,
            .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident) %>%
  mutate(per =  prop.table(n)) %>%
  dplyr::select(orig.ident,
                cloneType_airr_short,
                per) %>%
  pivot_wider(names_from = c(cloneType_airr_short), 
              values_from = per,
              values_fill = 0)


# clonotypes for cell type fine
ctype_fine <- gex.slim@meta.data %>% 
  select(orig.ident, cluster_cellType_manual_fine, cloneType_airr_short, c_gene_10x) %>%
  drop_na() %>%
  select(orig.ident, cluster_cellType_manual_fine, cloneType_airr_short)  %>%
  add_count(orig.ident, 
            cluster_cellType_manual_fine,
            cloneType_airr_short,
            .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident, cluster_cellType_manual_fine) %>%
  mutate(per =  prop.table(n)) %>%
  dplyr::select(orig.ident, 
                cluster_cellType_manual_fine,
                cloneType_airr_short,
                per) %>%
  pivot_wider(names_from = c(cluster_cellType_manual_fine, cloneType_airr_short), 
              values_from = per,
              values_fill = 0)
  
colnames(ctype_fine)[2:ncol(ctype_fine)] <- paste0(colnames(ctype_fine)[2:ncol(ctype_fine)], "_fine_clono")


# clonotypes for cell type main
ctype_main <- gex.slim@meta.data %>% 
  select(orig.ident, cluster_cellType_manual_main, cloneType_airr_short, c_gene_10x) %>%
  drop_na() %>%
  select(orig.ident, cluster_cellType_manual_main, cloneType_airr_short)  %>%
  add_count(orig.ident, 
            cluster_cellType_manual_main,
            cloneType_airr_short,
            .drop = FALSE) %>%
  distinct() %>%
  group_by(orig.ident, cluster_cellType_manual_main) %>%
  mutate(per =  prop.table(n)) %>%
  dplyr::select(orig.ident, 
                cluster_cellType_manual_main,
                cloneType_airr_short,
                per) %>%
  pivot_wider(names_from = c(cluster_cellType_manual_main, cloneType_airr_short), 
              values_from = per,
              values_fill = 0)
  
colnames(ctype_main)[2:ncol(ctype_main)] <- paste0(colnames(ctype_main)[2:ncol(ctype_main)], "_main_clono")


ctype <- inner_join(ctype_main, ctype_fine)


```


## concatenate vars object

```{r}

var_df <- 
  full_join(cells_fine, IGHV) %>%
  full_join(IGHD) %>%
  full_join(IGHJ) %>%
  full_join(IFN_main) %>%
  full_join(c_gene_10x_fine) %>%
  full_join(mu_fine) %>%
  full_join(ctype_all)

var_df <- var_df[-28, ]
var_df[is.na(var_df)] <- 0

#saveRDS(var_df, "../results/variables_per_patient.rds")
#var_df <- readRDS("../results/variables_per_patient.rds")

colnames(var_df)

#### !!!! Check column naming !!!!


```


## PCA (nipals)

```{r}


# main

#selecting variables with significant differences between patient groups
m <- apply(var_df[, 2:ncol(var_df)], 2, function(x){glm(x ~pheno$patient_group)} ) 
m <- lapply(m, summary)
m <- t(sapply(m, function(x){x$coefficients[2:4, 4]}))

sell1 <- rowMin(m)
sell <- rownames(m)[sell1 < 0.05]
colnames(pheno)
pc_df <- full_join(pheno[, c(1:2, 8:(ncol(pheno)-1))], var_df[, c("orig.ident", sell)])

rownames(pc_df) <- pc_df$orig.ident

# nipals package
pc_out <- nipals::nipals(pc_df[, 2:ncol(pc_df)], 
                       ncomp = 4, 
                       center = TRUE, 
                       scale = TRUE, 
                       fitted = FALSE, 
                       maxiter = 500, 
                       tol = 1e-9, 
                       gramschmidt = FALSE)

saveRDS(pc_out, "../results/pc_out_var_df.rds")


```


## plot PCA

```{r}

pc_out_sc <- as.data.frame(pc_out$scores)
pc_out_sc$orig.ident <- rownames(pc_out_sc)
pc_out_sc$patient_group <- pheno$patient_group

pc_out_ld <- as.data.frame(pc_out$loadings)
pc_out_ld$var <- rownames(pc_out_ld)

  #plot scores    
  p1.1 <- ggplot(pc_out_sc) + 
    geom_text_repel(size = 2.5,
                     aes(x = PC1, 
                         y = PC2, 
                         label = orig.ident, 
                         color = patient_group)) +
    xlab(paste0("PC1", " (", round(pc_out$eig[1], digits = 1), "%)")) +
    ylab(paste0("PC2", " (", round(pc_out$eig[2], digits = 1), "%)")) +
    geom_point(aes(x = PC1, y = PC2, color = patient_group)) +
    theme_classic() +
    geom_hline(yintercept = 0, linetype = 2, alpha = 0.4, size = 0.5) + 
    geom_vline(xintercept = 0, linetype = 2, alpha = 0.4, size = 0.5) +
    theme(legend.position = "none")
  
  p1.2 <- ggplot(pc_out_sc) + 
    geom_text_repel(size = 2.5,
                     aes(x = PC3, 
                         y = PC4, 
                         label = orig.ident, 
                         color = patient_group)) +
    xlab(paste0("PC3", " (", round(pc_out$eig[3], digits = 1), "%)")) +
    ylab(paste0("PC4", " (", round(pc_out$eig[4], digits = 1), "%)")) +
    geom_point(aes(x = PC3, y = PC4, color = patient_group)) +
    geom_hline(yintercept = 0, linetype = 2, alpha = 0.4, size = 0.5) + 
    geom_vline(xintercept = 0, linetype = 2, alpha = 0.4, size = 0.5) +
    theme_classic() +
    theme(legend.position = "none")
  
      # geom_segment(data = pc_out$loadings, 
      #            aes(x = 0, y = 0, xend = PC1, yend = PC2), 
      #            arrow = arrow(length = unit(0.2, "cm")), alpha = 0.25)

  #number of variables to display in barplot
  nvar <- 15
  
  #plot loadings PC1
  p2 <- pc_out_ld %>% 
    arrange(desc(PC1)) %>% 
    slice(c(1:nvar, (nrow(pc_out_ld)-nvar+1):nrow(pc_out_ld))) %>% 
    arrange(desc(PC1)) %>%
  ggplot(aes(x = PC1, 
             y = reorder(var, +PC1))) +
    ylab("") +
    geom_bar(stat = "identity") +
    theme_classic()
  
  
  #plot loadings PC2
  p3 <- pc_out_ld %>% 
    arrange(desc(PC2)) %>% 
    slice(c(1:nvar, (nrow(pc_out_ld)-nvar+1):nrow(pc_out_ld))) %>% 
    arrange(desc(PC2)) %>%
  ggplot(aes(x = PC2, 
             y = reorder(var, +PC2))) +
    ylab("") +
    geom_bar(stat = "identity")+
    theme_classic()
  
  
ggsave2(paste0("../results/Fig6_A-C.png"),
          plot_grid(p1.1, p2, p3, 
                    nrow = 1, 
                    ncol = 3, 
                    labels = NULL, 
                    align = "h", 
                    rel_widths = c(1.5, 1, 1)) + 
          bgcolor("white") + 
          border("white"),
          width = 30, height = 12, unit = "cm")


# merge PCA output with input for plotting
pc_out_sc <- full_join(pc_out_sc, pc_df)

# PC1
p_list_PC1 <- list()
for (i in 6:18){

  tmp <- select(pc_out_sc,
                colnames(pc_out_sc)[i], 
                PC1) %>% 
    drop_na()
  
  p_list_PC1[[colnames(pc_out_sc)[i]]] <- ggplot(tmp, 
                        aes_string(x = as.factor(tmp[, colnames(pc_out_sc)[i]]), 
                                   y = "PC1")) +
    geom_boxplot(na.rm = TRUE) +
    xlab(colnames(pc_out_sc)[i]) +
    theme_classic() 
  
}

for (i in 19:ncol(pc_out_sc)){
  
  tmp <- select(pc_out_sc, 
                colnames(pc_out_sc)[i], 
                PC1, 
                patient_group) %>%
    drop_na()
  
  p_list_PC1[[colnames(pc_out_sc)[i]]] <- ggplot(tmp, 
                                             aes_string(x = tmp[, colnames(pc_out_sc)[i]], 
                                                        y = "PC1",
                                                        color = "patient_group"
                                                        )) +
    geom_point(na.rm = TRUE) +
    #geom_smooth(method = lm, se = FALSE ) +
    #stat_cor(method="pearson") +
    xlab(colnames(pc_out_sc)[i]) +
    theme_classic() +
    theme(legend.position = "none")
  
}

var_PC1 <- pc_out_ld %>% 
    arrange(desc(PC1)) %>% 
    slice(c(1:nvar, (nrow(pc_out_ld)-nvar+1):nrow(pc_out_ld))) %>% 
    arrange(desc(PC1))
var_PC1$var



# PC2
p_list_PC2 <- list()
for (i in 6:18){

  tmp <- select(pc_out_sc,
                colnames(pc_out_sc)[i], 
                PC2) %>% 
    drop_na()
  
  p_list_PC2[[colnames(pc_out_sc)[i]]] <- ggplot(tmp, 
                        aes_string(x = as.factor(tmp[, colnames(pc_out_sc)[i]]), 
                                   y = "PC2")) +
    geom_boxplot(na.rm = TRUE) +
    xlab(colnames(pc_out_sc)[i]) +
    theme_classic() 
  
}

for (i in 19:ncol(pc_out_sc)){
  
  tmp <- select(pc_out_sc, 
                colnames(pc_out_sc)[i], 
                PC2, 
                patient_group) %>%
    drop_na()
  
  p_list_PC2[[colnames(pc_out_sc)[i]]] <- ggplot(tmp, 
                                             aes_string(x = tmp[, colnames(pc_out_sc)[i]], 
                                                        y = "PC2",
                                                        color = "patient_group"
                                                        )) +
    geom_point(na.rm = TRUE) +
    #geom_smooth(method = lm, se = FALSE ) +
    #stat_cor(method="pearson") +
    xlab(colnames(pc_out_sc)[i]) +
    theme_classic() +
    theme(legend.position = "none")
  
}

var_PC2 <- pc_out_ld %>% 
    arrange(desc(PC2)) %>% 
    slice(c(1:nvar, (nrow(pc_out_ld)-nvar+1):nrow(pc_out_ld))) %>% 
    arrange(desc(PC2))
var_PC2$var


ggsave2(paste0("../results/SFig15_PC1.png"),
          plot_grid(plotlist = p_list_PC1[var_PC1$var], 
                    nrow = 5, 
                    ncol = 5, 
                    labels = NULL, 
                    align = "hv") + 
          bgcolor("white") + 
          border("white"),
          width = 30, height = 25, unit = "cm")

ggsave2(paste0("../results/SFig15_PC2.png"),
          plot_grid(plotlist = p_list_PC2[var_PC2$var], 
                    nrow = 5, 
                    ncol = 5, 
                    labels = NULL, 
                    align = "hv") + 
          bgcolor("white") + 
          border("white"),
          width = 30, height = 25, unit = "cm")




plot_grid(plotlist = p_list[c(2:13, 1)], nrow = 4, ncol = 4)
plot_grid(plotlist = p_list[c(14:22)], nrow = 3, ncol = 3)
plot_grid(plotlist = p_list[c(23:40)], nrow = 4, ncol = 4)
plot_grid(plotlist = p_list[c(41:44)], nrow = 2, ncol = 2)


```



## Save rds GEX_xxx

```{r}

#saveRDS(gex, file = "../results/GEX_xxx.rds")

```


## Print sessionInfo()

```{r}

sessionInfo()

```



